package db;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author M.m
 */
public class NewJFrame extends javax.swing.JFrame {
      public RandomAccessFile raf;
      public String spaces="                                                            ";
      public long pos=0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame()  {
       try {
            initComponents();
            raf=new RandomAccessFile(new File("data.txt"), "rw");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(7, 2, 5, 5));

        jLabel1.setText("PC NAME :");
        getContentPane().add(jLabel1);
        getContentPane().add(jTextField1);

        jLabel2.setText("CPU SPEED :");
        getContentPane().add(jLabel2);
        getContentPane().add(jTextField2);

        jLabel3.setText("BRAND :");
        getContentPane().add(jLabel3);
        getContentPane().add(jTextField3);

        jLabel4.setText("RAM :");
        getContentPane().add(jLabel4);
        getContentPane().add(jTextField4);

        jLabel5.setText("MADE DATE :");
        getContentPane().add(jLabel5);
        getContentPane().add(jTextField5);

        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setText("SAVE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);

        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);

        jButton4.setText("UPDATE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         String target = "";
                if (!jTextField1.getText().equals("")) target = jTextField1.getText();
                else if (!jTextField2.getText().equals("")) target = jTextField2.getText();
                else if (!jTextField3.getText().equals("")) target = jTextField3.getText();
                else if (!jTextField4.getText().equals("")) target = jTextField4.getText();
                else if (!jTextField5.getText().equals("")) target = jTextField5.getText();
                if (!target.equals("")) {
                    try {
                        String curr = null;
                        pos = 0;
                        raf.seek(0);
                        boolean found = false;
                        ArrayList<String> arr = null;
                        while ((curr = raf.readLine()) != null) {

                            StringTokenizer st = new StringTokenizer(curr.trim(), ",");
                            arr = new ArrayList<String>();
                            while (st.hasMoreTokens()) {
                                arr.add(st.nextToken().trim());
                            }
                            if (arr.contains(target)) {
                                found = true;
                                break;
                            }

                            pos = raf.getFilePointer();
                        }

                        if (curr == null) JOptionPane.showMessageDialog(null, "Car not found!");
                        else {
                            jTextField1.setText(arr.get(0));
                            jTextField2.setText(arr.get(1));
                            jTextField3.setText(arr.get(2));
                            jTextField4.setText(arr.get(3));
                            jTextField5.setText(arr.get(4));
                        }


                    } catch (IOException ex) {
                        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }

                } else JOptionPane.showMessageDialog(null, "Enter some data for the search!");

            
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         try {
                    String data = jTextField1.getText() + "," + jTextField2.getText() + "," + jTextField3.getText() + "," + jTextField4.getText() + "," + jTextField5.getText() + "spaces" + "\r\n";
                    raf.seek(raf.length());
                    raf.writeBytes(data);
                    JOptionPane.showMessageDialog(null, "Car saved successfully!");
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         try {
                    // TODO add your handling code here:
                    raf.seek(pos);
                    int length = raf.readLine().trim().length();
                    raf.seek(pos);
                    for (int i = 0; i < length; i++) {
                        raf.writeBytes(" ");
                    }
                    raf.seek(pos);
                    JOptionPane.showMessageDialog(null, "car deleted successfully!");
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         try {
                    // TODO add your handling code here:
                    raf.seek(pos);
                    int length = raf.readLine().trim().length();
                    raf.seek(pos);
                    for (int i = 0; i < length; i++) {
                        raf.writeBytes(" ");
                    }
                    raf.seek(pos);

                    String data = jTextField1.getText() + "," + jTextField2.getText() + "," + jTextField3.getText() + "," + jTextField4.getText() + "," + jTextField5.getText();
                    raf.writeBytes(data);
                    raf.seek(pos);
                    JOptionPane.showMessageDialog(null, "Data updated successfully!");

//           System.out.println(pos);
//           System.out.println(raf.getFilePointer());
                } catch (IOException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration                   
}

